services:
  app:
    build: ./crm
    container_name: crm-app
    restart: unless-stopped
    env_file:
      - ./crm/.env
    networks:
      - default

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - default
    depends_on:
      - app

  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    environment:
      - WEBHOOK_URL=https://n8n.megarubberduck.it
      - GENERIC_TIMEZONE=Europe/Rome
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - default

volumes:
  caddy_data:
  caddy_config:
  n8n_data:

networks:
  default:
    name: n8n-server_default
